/**
 * Generates per-area barrel files (`<area>.impl.ts` and `<area>.global.ts`) that
 * re-export every helper in that area's subdirectories.
 *
 * For each root in BARREL_ROOTS, the script looks at `<root>/<sub>/<sub>.impl.ts`
 * (and the matching `.global.ts`) and emits one re-export per subdirectory:
 *   - `export { name } from "./<sub>/<sub>.impl"` when one export matches the basename
 *   - `export * from "./<sub>/<sub>.impl"`        when multiple exports (none matches)
 *   - `import "./<sub>/<sub>.global"`             for every global barrel entry
 *
 * Also generates `src/temporal/temporal.global.ts` which imports every per-area
 * `<sub>/<sub>.global.ts` (including hand-written ones like `interval`).
 *
 * Usage:
 *   yarn tsx scripts/generate-barrels.ts          # regenerate all
 *   yarn tsx scripts/generate-barrels.ts --check  # exit non-zero if out of date (for CI)
 */
import * as fs from "fs";
import * as path from "path";
import { Project } from "ts-morph";

const SRC_DIR = path.join(__dirname, "..", "src");
const CHECK_MODE = process.argv.includes("--check");

const BARREL_ROOTS: { dir: string; barrelName: string }[] = [
  { dir: "array", barrelName: "array" },
  { dir: "map", barrelName: "map" },
  { dir: "temporal/plainDate", barrelName: "plainDate" },
  { dir: "temporal/zonedDateTime", barrelName: "zonedDateTime" },
  { dir: "temporal/legacyDate", barrelName: "legacyDate" },
];

const project = new Project({ skipFileDependencyResolution: true });

interface ImplEntry {
  subdir: string;
  base: string;
  primaryExport: string | undefined;
}

interface GlobalEntry {
  subdir: string;
  base: string;
}

function listExports(filePath: string): string[] {
  const sf = project.addSourceFileAtPath(filePath);
  const names = [...sf.getExportedDeclarations().keys()];
  project.removeSourceFile(sf);
  return names;
}

function discoverImpls(rootDir: string): ImplEntry[] {
  const root = path.join(SRC_DIR, rootDir);
  return fs
    .globSync(path.join(root, "*/*.impl.ts"))
    .map((implPath): ImplEntry => {
      const subdir = path.basename(path.dirname(implPath));
      const base = path.basename(implPath, ".impl.ts");
      const exports = listExports(implPath);
      return { subdir, base, primaryExport: exports.find((n) => n === base) };
    })
    .sort((a, b) => a.subdir.localeCompare(b.subdir));
}

function discoverGlobals(rootDir: string): GlobalEntry[] {
  const root = path.join(SRC_DIR, rootDir);
  return fs
    .globSync(path.join(root, "*/*.global.ts"))
    .map((globalPath) => ({
      subdir: path.basename(path.dirname(globalPath)),
      base: path.basename(globalPath, ".global.ts"),
    }))
    .sort((a, b) => a.subdir.localeCompare(b.subdir));
}

function renderImplBarrel(entries: ImplEntry[]): string {
  return (
    entries
      .map((e) =>
        e.primaryExport
          ? `export { ${e.primaryExport} } from "./${e.subdir}/${e.base}.impl";`
          : `export * from "./${e.subdir}/${e.base}.impl";`,
      )
      .join("\n") + "\n"
  );
}

function renderGlobalBarrel(entries: GlobalEntry[]): string {
  return entries.map((e) => `import "./${e.subdir}/${e.base}.global";`).join("\n") + "\n";
}

function processRoot(rootDir: string, barrelName: string): { path: string; content: string }[] {
  const root = path.join(SRC_DIR, rootDir);
  const out: { path: string; content: string }[] = [];
  const impls = discoverImpls(rootDir);
  if (impls.length > 0) {
    out.push({ path: path.join(root, `${barrelName}.impl.ts`), content: renderImplBarrel(impls) });
  }
  const globals = discoverGlobals(rootDir);
  if (globals.length > 0) {
    out.push({ path: path.join(root, `${barrelName}.global.ts`), content: renderGlobalBarrel(globals) });
  }
  return out;
}

function processTemporalGlobal(generatedPaths: Set<string>): { path: string; content: string } {
  const temporalDir = path.join(SRC_DIR, "temporal");
  // Include every subdir whose `<sub>/<sub>.global.ts` will exist after this
  // run — either generated by us or already on disk (e.g. hand-written interval).
  const subdirs = fs
    .readdirSync(temporalDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((d) => {
      const globalPath = path.join(temporalDir, d, `${d}.global.ts`);
      return generatedPaths.has(globalPath) || fs.existsSync(globalPath);
    })
    .sort();
  const content = subdirs.map((d) => `import "./${d}/${d}.global";`).join("\n") + "\n";
  return { path: path.join(temporalDir, "temporal.global.ts"), content };
}

function main(): void {
  const outputs: { path: string; content: string }[] = BARREL_ROOTS.flatMap(({ dir, barrelName }) =>
    processRoot(dir, barrelName),
  );
  outputs.push(processTemporalGlobal(new Set(outputs.map((o) => o.path))));

  let allMatch = true;
  for (const { path: outPath, content } of outputs) {
    const rel = path.relative(SRC_DIR, outPath);
    if (CHECK_MODE) {
      if (!fs.existsSync(outPath) || fs.readFileSync(outPath, "utf-8") !== content) {
        console.error(`MISMATCH: ${rel}`);
        allMatch = false;
      }
    } else {
      fs.writeFileSync(outPath, content);
      console.log(`Generated: ${rel}`);
    }
  }

  if (CHECK_MODE) {
    if (allMatch) {
      console.log("All barrels are up to date.");
      process.exit(0);
    } else {
      console.error("\nBarrels are out of date. Run `yarn tsx scripts/generate-barrels.ts` to regenerate.");
      process.exit(1);
    }
  } else {
    console.log("\nDone!");
  }
}

main();
